spring.application.name=demo
server.port=8081
spring.mongodb.uri=mongodb://localhost:27018/twitter-clone
jwt.secret=change-me-in-production-change-me-in-production
jwt.expiration=86400000
spring.data.mongodb.auto-index-creation=true
